language: java

jdk:
  - oraclejdk7
  - oraclejdk8

after_success:
  - mvn clean
  - test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_JDK_VERSION}" == "oraclejdk7" && mvn -Dmaven.test.skip=true deploy --settings travis-settings.xml

branches:
  only:
    - master
      # Build tags that match this regex in addition to building the master branch.
    - /^gml3-jts-[0-9]+\.[0-9]+\.[0-9]+/
