language: java

jdk:
  - oraclejdk7
  - oraclejdk8

deploy:
  provider: script
  script: mvn -Dmaven.test.skip=true deploy --settings travis-settings.xml
  on:
    tags: true
    jdk: oraclejdk7

cache:
  directories:
  - $HOME/.m2
